name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  challenge-1:
    name: challenge 1
    env:
      working-directory: ./challenge-1/ccwc

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
      working-directory: ${{env.working-directory}}
    - name: Run tests
      run: cargo test --verbose
      working-directory: ${{env.working-directory}}
      
  challenge-2:
    name: challenge 2
    env:
      working-directory: ./challenge-2/json-parser

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
      working-directory: ${{env.working-directory}}
    - name: Run tests
      run: cargo test --verbose
      working-directory: ${{env.working-directory}}
    - name: Run integration tests
      run: ./tests/integration_test.sh
      working-directory: ${{env.working-directory}}
